name: Generate Snake Game

on:
  schedule:
    - cron: "0 */12 * * *" # a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Atualizar Snake
    runs-on: ubuntu-latest

    steps:
      - name: Gerar animação do Snake
        uses: Platane/snk@v3
        with:
          github_user_name: MarioCcomp
          outputs: |
            dist/github-contribution-grid-snake.svg
          color_snake: '#8b5cf6'
          color_dots: '#161b22,#0e4429,#006d32,#26a641,#39d353'

      - name: Deploy para o branch output
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
